# Generated by Django 5.2.1 on 2025-06-04 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todoitem_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='project',
        ),
    ]
