# Generated by Django 5.2.2 on 2025-06-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprf', '0002_mprfrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mprfrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
