# Generated by Django 5.2.2 on 2025-06-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mprf', '0005_mprfapply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mprfapply',
            name='Skills',
        ),
    ]
