# Generated by Django 5.2.2 on 2025-06-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mprf', '0006_remove_mprfapply_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mprfapply',
            name='resume',
        ),
    ]
