# Generated by Django 5.2.2 on 2025-06-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprf', '0007_remove_mprfapply_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='mprfapply',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('interview', 'Interview Scheduled'), ('offer', 'Offer Made'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='submitted', max_length=20),
        ),
    ]
