# Generated by Django 5.2.2 on 2025-06-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprf', '0010_mprfapply_aadhaar_number_mprfapply_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mprfapply',
            name='img_candidate',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
