# Generated by Django 5.2.2 on 2025-06-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprf', '0011_mprfapply_img_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mprfapply',
            name='resume',
            field=models.FileField(default=1, upload_to='resumes'),
            preserve_default=False,
        ),
    ]
