# Generated by Django 5.2.2 on 2025-06-07 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprf', '0013_employeemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='mprf_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mprf.mprfrequest'),
        ),
    ]
