# Generated by Django 5.2.2 on 2025-06-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mprf', '0015_employeemaster_application_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemaster',
            name='application_id',
        ),
    ]
