# Generated by Django 5.2.2 on 2025-06-07 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprf', '0016_remove_employeemaster_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='application_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mprf.mprfapply'),
        ),
    ]
