# Generated by Django 5.2.2 on 2025-06-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprf', '0017_employeemaster_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
