# Generated by Django 5.2.2 on 2025-06-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mprf', '0018_employeemaster_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemaster',
            name='created_at',
        ),
    ]
