# Generated by Django 5.2.2 on 2025-06-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoo',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
